### ISSUE TITLE
host

### ISSUE THREAD

**Issue by ulamnet** [zoff-music/zoff-server#4]
where is the best host for server installation? Normal hosting working ?

**Comment by kasperrt** [comment]
Yes, that should work. Depends on what you're planning on doing with the server and frontend

**Comment by ulamnet** [comment]
how to depends ? ı install all system requiestments , but how to get files ? sorry my bad english friend :)

**Comment by kasperrt** [comment]
What do you mean by getting the files? You have to clone the repository, and run the server with node.js. How to set up the server should be in the README.md
